spring.datasource.url=jdbc:tc:postgresql:15:///orders
spring.datasource.driver-class-name=org.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

payment.service.url=http://localhost:9998
auth.service.url=http://localhost:9999

server.port=0